# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weather_pb2 as weather__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in weather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub:
    """---------------- services ----------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/weather.Coordinator/Configure',
                request_serializer=weather__pb2.StreamConfig.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)
        self.StreamRecords = channel.stream_unary(
                '/weather.Coordinator/StreamRecords',
                request_serializer=weather__pb2.RecordBatch.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)
        self.GetAnalytics = channel.unary_unary(
                '/weather.Coordinator/GetAnalytics',
                request_serializer=weather__pb2.AnalyticsRequest.SerializeToString,
                response_deserializer=weather__pb2.AnalyticsReply.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/weather.Coordinator/Shutdown',
                request_serializer=weather__pb2.Empty.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)


class CoordinatorServicer:
    """---------------- services ----------------

    """

    def Configure(self, request, context):
        """sends the header of the dataset and resets all analytics (call it before every stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRecords(self, request_iterator, context):
        """the client streams the records in batches; returns when all records are processed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalytics(self, request, context):
        """current analytics, can be called while the stream is running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """stops the coordinator and all its workers (used by the scripts)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=weather__pb2.StreamConfig.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
            'StreamRecords': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamRecords,
                    request_deserializer=weather__pb2.RecordBatch.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=weather__pb2.AnalyticsRequest.FromString,
                    response_serializer=weather__pb2.AnalyticsReply.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=weather__pb2.Empty.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator:
    """---------------- services ----------------

    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Coordinator/Configure',
            weather__pb2.StreamConfig.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRecords(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/weather.Coordinator/StreamRecords',
            weather__pb2.RecordBatch.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Coordinator/GetAnalytics',
            weather__pb2.AnalyticsRequest.SerializeToString,
            weather__pb2.AnalyticsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Coordinator/Shutdown',
            weather__pb2.Empty.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/weather.Worker/Configure',
                request_serializer=weather__pb2.WorkerConfig.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)
        self.ProcessBatch = channel.unary_unary(
                '/weather.Worker/ProcessBatch',
                request_serializer=weather__pb2.RecordBatch.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)
        self.GetPartial = channel.unary_unary(
                '/weather.Worker/GetPartial',
                request_serializer=weather__pb2.Empty.SerializeToString,
                response_deserializer=weather__pb2.PartialStats.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/weather.Worker/Shutdown',
                request_serializer=weather__pb2.Empty.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)


class WorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=weather__pb2.WorkerConfig.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
            'ProcessBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBatch,
                    request_deserializer=weather__pb2.RecordBatch.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
            'GetPartial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartial,
                    request_deserializer=weather__pb2.Empty.FromString,
                    response_serializer=weather__pb2.PartialStats.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=weather__pb2.Empty.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Worker/Configure',
            weather__pb2.WorkerConfig.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Worker/ProcessBatch',
            weather__pb2.RecordBatch.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Worker/GetPartial',
            weather__pb2.Empty.SerializeToString,
            weather__pb2.PartialStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.Worker/Shutdown',
            weather__pb2.Empty.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
